#!/bin/bash -e

REMOTE="127.0.0.1:10000"

TYPE=$1; SUBTYPE=$2; JID=$3; FILE=$4
#echo "$TYPE $SUBTYPE $JID $FILE" >> ~/.mcabber/mcabber.log

if [ "$TYPE" == "MSG" ] && [ "$SUBTYPE" == "IN" ]; then
  echo -e "normal\nJaber\nMessage from $JID\n\n" | socat TCP:$REMOTE -
fi

exit 0
